### ISSUE TITLE
hey nice code

### ISSUE THREAD

**Issue by TrisanHuynh** [Botany-Downs-Secondary-College/password_manager-brian-huang-_#3]
bottom text

**Comment by brianh727** [comment]
not funny, told the TEACAHER about YOUR comment, not awesome.
signed, Ravi G: swagger of coolness

**Comment by TrisanHuynh** [comment]
![image](https://user-images.githubusercontent.com/78832252/112915790-a1f26180-915b-11eb-8ab8-ac54bbc8ea00.png)

cat

**Comment by TrisanHuynh** [comment]
uhhh whoops it meant to be a cat

cat

**Comment by TrisanHuynh** [comment]
=^._.^=
